version: "3.9"

services:
    backend:
        build: ./backend
        container_name: flask-backend
        ports:
            - "8000:8000"
        environment:
            - FLASK_ENV=production
        volumes:
            - ./backend:/app
        restart: unless-stopped

    frontend:
        build: ./frontend
        container_name: react-frontend
        ports:
            - "3000:80"
        depends_on:
            - backend
        restart: unless-stopped
